### PR TITLE
chore(types): Update to Github Action CI lib

### PR DESCRIPTION
**Pull request by nina-py**
## Goal

Let the new prospect type be used on the frontend.

Note: failing test is flaky and is irrelevant to the changes in this PR: https://github.com/Pocket/curation-admin-tools/blob/6b990ade40f4815f370eda2b0409e4b225d2b85d/src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.test.tsx#L45

## Reference

https://mozilla-hub.atlassian.net/browse/MC-224

### CODE REVIEW

**Review by rolf-moz — DISMISSED** [review]

**Comment by rolf-moz** [comment]
The type updates originally in this PR were already merged in another PR today, so not much left here.
Nina do the ci changes need to go in?

**Comment by nina-py** [comment]
Hi @rolf-moz, ideally they should as the old GitHub actions have been deprecated for a while and were running on a no longer supported version of Node.

**Comment by nina-py** [comment]
I'd update the commit message as you merge and squash those commits to reflect the actual changes going in and not the type updates that are already in

**Comment by rolf-moz** [comment]
@nina-py I confirmed on the main and on this branch the graphql type autogeneration is working now.
It must have been a temporary outage, since it was broken for Herraj and myself. I'll merge the CI change on Monday

**Pull request closed without merging**
